### ISSUE TITLE
Mismatch on documentation and methods

### ISSUE THREAD

**Issue by lmullen** [lmullen/gender#47]
> I wanted to report that the documentation is a bit out sync with the code. The documentation gives "genderize" and "kantrowitz" as possible methods, but if you use those the code returns the following error:
Error in match.arg(method) : 
  'arg' should be one of “ssa”, “ipums”, “napp”, “demo”

**Comment by Moohan** [comment]
Assume this refers to `gender_df()` this function could also be updated to take country (where appropriate) and pass through to `gender()`
