### ISSUE TITLE
Installing genderdata package instructions

### ISSUE THREAD

**Issue by elinw** [lmullen/gender#63]
This is the message that I got saying to install genderdata.

> The genderdata package needs to be installed.
> Install the genderdata package? 
> 
> 1: Yes
> 2: No
> 
> Selection: 1
> Installing the genderdata package.
> Error in value[[3L]](cond) : Failed to install the genderdata package.
>   Please try installing the package for yourself using the following command: 
>      install.packages("genderdata", repos = "https://dev.ropensci.org", type = "source")
> 

So I did that. 

```
 install.packages("genderdata", repos = "https://dev.ropensci.org", type = "source")
```
>Error in install.packages : error reading from connection

So I tried

```
install.packages("genderdata", repos = "http://packages.ropensci.org")
````
and that worked.

Maybe that should be changed? 

https://github.com/ropensci/gender/blob/master/R/install-genderdata-package.R#L23

**Comment by Moohan** [comment]
I had the same issue and the same fix.

**Comment by tiskawn** [comment]
I have the same issue, but the suggested fix:

`install.packages("genderdata", repos = "http://packages.ropensci.org")`
 
is not working and just doesn't return anything when entered. 

Any suggestions?

**Comment by lmullen** [comment]
I am aware of this issue and will fix it when I get a chance. The package recently was moved away from rOpenSci. 

In the meantime, you can install the packages like so:

```
install.packages("remotes") # if necessary
remotes::install_github("lmullen/gender")
remotes::install_github("lmullen/genderdata")
```

**Comment by lmullen** [comment]
You should be able to install the development version with `remotes::install_github("lmullen/gender")`, which will then help you install any other necessary packages.
